### ISSUE TITLE
Running on multi-fasta

### ISSUE THREAD

**Issue by niederhuth** [gsneha26/SegAlign#45]
First off, thank you so much for this tool. The speed-up compared to lastz is incredible and this is allowing me to accomplish in mere minutes and hours what was taking days or more with lastz alone. 

I was hoping you give me some advice on running this for a whole genome alignment. With the original lastz, you can input your target as a multi-fasta, however it strongly recommended that you do not provide a multi-fasta as a query. Does this hold true with SegAlign if you use the run_segalign.sh script? It appears to me that this script breaks the sequences down into segments. So would it be ok to run a fasta with all chromosomes of a genome against another fasta with all chromosomes of another genome or would you advice breaking the query fasta down by each sequence in the fasta file?

Thank you for your time.

**Comment by rsharris** [comment]
`With the original lastz, you can input your target as a multi-fasta, however it strongly recommended that you do not provide a multi-fasta as a query.`

I'm the guy who wrote lastz, and what I'm about to write only applies to lastz.

I think that (i.e. the notion that you should not provide a multi-fasta as a query) is a misconception resulting from what in retrospect was a poor human-interface design choice I made. Leaving the [multiple] _designation_ off the query file is recommended, regardless of whether the query file has one or more sequences. So if target and query both have more than one sequence, this is the recommended command:
`lastz target.fa[multiple] query.fa`

The [multiple] designation tells lastz to collect all the sequences from that file into one long sequence in memory. It is necessary that lastz have all the target sequences in memory, but for the query it only needs them in memory one at a time.

It would have made more sense for lastz to figure out whether the file contained more than one sequence and do what it needed to do without the user having to tell it. Unfortunately I decided there was a cost in doing that. In retrospect that cost is extremely minimal — it was a bad choice on my part, and it has led to confusion.

**Comment by gsneha26** [comment]
Thank you @niederhuth, we are glad that the tool is so helpful for your research.

I am slightly confused by what you mean by ` would you advice breaking the query fasta down by each sequence in the fasta file`.

If I understand your question correctly, the following should help:
For SegAlign, we recommend that you do provide multiple chromosomes for both, the target and the query. There are internal optimizations that overlap the different alignment stages for different chromosome-pairs which helps in maximum resource utilization and provides higher speedup. ( If you are interested in knowing more about these optimizations, you can have a look at our paper - https://doi.ieeecomputersociety.org/10.1109/SC41405.2020.00043 ). 

About the `run_segalign.sh` script -- it essentially handles the seed-filter and extend stages, where the seed-filter stages are run using the `segalign` executable (GPU accelerated), the output `segment` files are generated, and then, the extend stage is run using `lastz`. In order to get the alignments and not just the segment files, you always need to use  `run_segalign.sh` and not just the `segalign` executable.
